services:
  redis: # 레디스 설정
    image: redis:7
    container_name: finly-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  backend:
    build: .
    image: finly-backend
    container_name: finly-backend
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_TOKEN_EXPIRE_MS: ${JWT_ACCESS_TOKEN_EXPIRE_MS}
      JWT_REFRESH_TOKEN_EXPIRE_MS: ${JWT_REFRESH_TOKEN_EXPIRE_MS}
      KIS_KOSPI_URL: ${KIS_KOSPI_URL}
      KIS_KOSDAQ_URL: ${KIS_KOSDAQ_URL}
      TRADINGVIEW_SYMBOL_URL: ${TRADINGVIEW_SYMBOL_URL}
      TRADINGVIEW_S3_LOGO_URL: ${TRADINGVIEW_S3_LOGO_URL}
      APP_CORS_ALLOWED_ORIGINS: ${APP_CORS_ALLOWED_ORIGINS}
      KI_BASE_URL: ${KI_BASE_URL}
      KI_APP_KEY: ${KI_APP_KEY}
      KI_APP_SECRET: ${KI_APP_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      REDIS_HOST: finly-redis
      REDIS_PORT: 6379
      IMAGE_UPLOAD_DIR: /data/finly-images
    ports:
      - "8080:8080"
    restart: always

    volumes:
      - /home/ubuntu/finly-images:/data/finly-images

volumes:
  mysql-data:
  redis-data: