spring:
  config:
    import: optional:file:./.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show_sql: false
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

image:
  upload-dir: ${IMAGE_UPLOAD_DIR:/data/finly-images}

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS}
  cookie:
    secure: true
    same-site: None
    path: /
