spring:
  application:
    name: finly

jwt:
  secret: ${JWT_SECRET:VGhpcy1pcy1hLWxvY2FsLWRldi1zZWNyZXQtdGhhdC1pcy1iYXNlNjQ=}
  access-token-expire-ms: ${JWT_ACCESS_TOKEN_EXPIRE_MS:3600000}
  refresh-token-expire-ms: ${JWT_REFRESH_TOKEN_EXPIRE_MS:1209600000

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
